### PR TITLE
docs: add app sketch for section 4 in the proposal

### LINKED ISSUE #5: Proposal: Section 4 - App sketch & brief description
Create a sketch of what you envision your app to look like. Your sketch can be hand-drawn or put together using a graphics editor or slide show software. The sketch should be saved as img/sketch.png and linked in this section of the proposal so that the image shows up when reading the proposal on GitHub.

Complement the sketch with a high level description of the main components in the app interface and how the user will interact with it. You are not required to use terminology specific to Dash/Shiny (i.e. widgets, components, etc...).

Remember to be realistic about your expectations and plans since you will actually be implementing this app (but again, you will not be penalized if you need to adjust a bit in later milestones). It is better to design a slightly more limited app that you have time to implement well, instead of a complicated app that you don't have time to finish. At the same time, you cannot just make a single bar chart and call it a day; the app needs to have several input and output panels. You can view the dashboards from previous years students in the [DSCI 532 showcase](https://five32-dashboard-showcase.onrender.com/) (might take several seconds to load) as a complexity target and to get inspiration for your final app. Your TA will be able to help you with this as well, and provide feedback on whether your app is too simple or too complex.

### LINKED ISSUE #16: Repository structure: img/sketch.png

### PR DESCRIPTION
**Pull request by JohnShiuMK**
added drafts of app sketch for section 4 in the proposal, to be discussed tmr

### CODE REVIEW

**Review by tonyshumlh — COMMENTED** [review]
We can add Big Figures chart, e.g. Rice Price $20/{unit}  {Down Symbol} 5% compared to last month {Down Symbol} 2% compared to last year
Sample

**Comment by srfrew** [comment]
This looks great! I think these two main views cover our key functionality. 
A couple recommendations that may not need to be included in the photo, but could be considered: 
- Advanced Geospatial View: Add an option for regional heatmaps in datasets and the ability to select specific regions
- Basic view: Overall layout with widget bar looks great. I recommend placing the food price index chart on top with individual charts and statistics on the bottom, so users can look to them for a more detailed view. As more markets are selected, the extra charts can overflow and users can scroll

**Review by srfrew — CHANGES_REQUESTED** [review]
Main request would be to flip the layout of the basic view so that the geometric mean is on top as it is the most general chart, and other charts below so scrolling can be enabled. 

See PR comment for more details

**Comment by JohnShiuMK** [comment]
this one has been merged into #23 already

**Pull request closed without merging**
