### PR TITLE
docs: edit m1_EDA

### LINKED ISSUE #13: EDA on the data (Repository structure: notebooks/)
please upload our EDA-related notebooks to notebooks/

### PR DESCRIPTION
**Pull request by celestezhao**

### CODE REVIEW

**Comment by JohnShiuMK** [comment]
That's impressive!! lolllll

**Comment by JohnShiuMK** [comment]
@tonyshumlh @srfrew 
I think it's very comprehensive, what do you guys think?

**Comment by srfrew** [comment]
I will have a closer look tomorrow but at a glance it appears very well done and comprehensive! Great work @celestezhao!!

**Review by srfrew — APPROVED** [review]
Reviewed locally, EDA is comprehensive and highlights interesting trends for next milestones!

**Pull request merged**
